### ISSUE TITLE
Incorrect pose conversion code

### ISSUE THREAD

**Issue by zhengqili** [ken2576/multiview_preprocessing#1]
I think the conversion function from LLFF to OpenCV is somehow incorrect.

The correct version (after using this code, the poses & reconstruction look correct to me from COLMAP)

    def convert_llff(pose):
      hwf = pose[:3, 4:] 

      ext = np.eye(4)

      ext[:3, :4] = pose[:3, :4]

      ext = np.concatenate([ext[:, 1:2], 
                          ext[:, 0:1], 
                          -ext[:, 2:3], 
                          ext[:, 3:4]], axis=1)

      mat = np.linalg.inv(ext)

      return np.concatenate([mat[:3, :4], hwf], -1)
`

**Comment by ken2576** [comment]
Hi Zhengqi,
Thanks for letting me know!
I will take a look and fix this ASAP.
